### ISSUE TITLE
Timing Attack Vulnerability

### ISSUE THREAD

**Issue by paragonie-scott** [RNCryptor/RNCryptor-python#1]
http://www.openwall.com/lists/oss-security/2016/01/24/10

* https://github.com/RNCryptor/RNCryptor-Spec/blob/04378bc27c604e97353badbead8c435698abe97a/RNCryptor-Spec-v3.md#consistent-time-equality-checking
* https://cryptocoding.net/index.php/Coding_rules#Compare_secret_strings_in_constant_time
* http://blog.ircmaxell.com/2014/11/its-all-about-time.html

Problematic line: https://github.com/RNCryptor/RNCryptor-python/blob/71031f243bcba2aaa7bca4ff9a4c01358427b476/RNCryptor.py#L87

**Comment by ykalchevskiy** [comment]
@paragonie-scott, thank you for the report. I just fixed it.
