### ISSUE TITLE
post_decrypt_data should return bytes

### ISSUE THREAD

**Issue by an0** [RNCryptor/RNCryptor-python#10]
https://github.com/RNCryptor/RNCryptor-python/blob/2004d7db34f1a91082b22a4a55cb2ee9e5e07a0d/rncryptor.py#L94

post_decrypt_data should return bytes because not all bytes can be decoded into string using utf-8 encoding. Here is the call stack:
  File "…/lib/python3.7/site-packages/rncryptor.py", line 122, in decrypt
    return self.post_decrypt_data(decrypted_data)
  File "…/lib/python3.7/site-packages/rncryptor.py", line 97, in post_decrypt_data
    return to_str(data)
  File "…/lib/python3.7/site-packages/rncryptor.py", line 44, in to_str
    return s.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte

If user is sure that the decrypted bytes can be decoded and wants string he can decode it himself.

**Comment by ykalchevskiy** [comment]
I agree, but it's hard to change the existing API because it's already in use. Check out #8 for a solution.
