### ISSUE TITLE
Do you plan on adding this to PyPI?

### ISSUE THREAD

**Issue by afilbert** [RNCryptor/RNCryptor-python#5]
I'm loading requirements of my app from `requirements.txt` and would like to avoid using the [editable packages syntax](https://pip.readthedocs.io/en/1.1/requirements.html#requirements-file-format) if at all possible. 

I envision my requirements looking something like this:

`RNCryptor-python==3.2.0`

Sorry if this is asked in the wrong place. Please feel free to close if that's the case, and let me know where I can submit questions like this.

**Comment by ykalchevskiy** [comment]
Hi,
I think it is the right place. Actually all is already prepared for PyPI. I've just waited for someone who is going to use it :) I will try to do it at weekend. Feel free to ping me If I am lost.

BTW, the name will be just `rncryptor`.

**Comment by ykalchevskiy** [comment]
Hi,
I've uploaded RNCryptor to PyPI: https://pypi.python.org/pypi/rncryptor

**Comment by afilbert** [comment]
Perfect. Thanks, @ykalchevskiy!

**Comment by ykalchevskiy** [comment]
You are welcome :)
