### ISSUE TITLE
Cross platform issue (Encrypt with Java, Decrypt with Python)

### ISSUE THREAD

**Issue by AzriDelta** [RNCryptor/RNCryptor-python#6]
If I encrypt a string in Java (using https://github.com/TGIO/RNCryptorNative) and try to decrypt it using RNCryptor-python, bad data error pops out.

Example (these information are not private)
```
Plaintext: Dewan Seri Mutiara
Encrypted text from Java: AgFbaUVITLbVwBdN8TAGNSRIDmtrkB1lvwhm0uRjdmK5gGPPuvemTFQs2djH5GLVNQyJzpSt8cFxLQ5JQK/QA83qpRYvyKFXY3BwWd2nX9dWU4fGIQ71Cg8ztVUZ4h+G9N8=
Encryption key and decryption key: MnRVlrkRtZqhT3QoKiYhEo/OBjV+IlRXiq8D9dEuXGM=
```
One thing that I notice is, if i use:
```
base64.b64decode(encrypted_data_from_java)
```
It will return a value that begins with

```
\x02\x01\<other strings>
```

While if I encrypt using RNCryptor-Python and decode the encrypted data, the byte will begin with

```
\x03\x01\<other strings>
```

Is this a version issue? As far as I know, RNCryptorNative is still in version 2.

**Comment by ykalchevskiy** [comment]
Yes, looks like a version issue in RNCryptorNative, because current version is 3:
https://github.com/RNCryptor/RNCryptor-Spec/blob/master/RNCryptor-Spec-v3.md
You may try https://github.com/RNCryptor/JNCryptor for Java.

**Comment by AzriDelta** [comment]
Okay. Thanks for the assistance.
