### ISSUE TITLE
There is a bug when decrypting the return string

### ISSUE THREAD

**Issue by wcyDreamer** [RNCryptor/RNCryptor-python#8]
i used python3, when i try to decrypt Binary stream file which i encrypted, there is a bug `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 13: invalid continuation byte`.This is because the binary stream format cannot be decoded by `UTF-8` directly.this is functions ```    def to_str(s):
        if isinstance(s, bytes):
            return s.decode('utf-8')
        if isinstance(s, str):
            return s```.

**Comment by rnapier** [comment]
What do you mean by "Binary stream file?" What type are you passing to decrypt?

**Comment by wcyDreamer** [comment]
1、“Binary stream file” for example: an audio file in`. mid` format.
2、i use `with open(file, 'rb') as f` to get the encrypted content so passing to  decrypt data type is binary data

**Comment by wcyDreamer** [comment]
[rncryptor_example.zip](https://github.com/RNCryptor/RNCryptor-python/files/2959310/rncryptor_example.zip)

**Comment by ykalchevskiy** [comment]
Oh, confirmed, there is a bug. There is an unneeded conversion. I will think how to fix it and do not affect existing users. Now for you I suggest the following:
```
import rncryptor

class BinaryRNCryptor(rncryptor.RNCryptor):
    def post_decrypt_data(self, data):
        return data[:-rncryptor.bord(data[-1])]

b = BinaryRNCryptor()
s = open('./source/two.mid', 'rb').read()
e = b.encrypt(s, p)
d = b.decrypt(e, p)
assert d == s
```

**Comment by wcyDreamer** [comment]
thanks very much
